server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #application:
   #name: userservice
#eureka:
 #client:
  #service-url:
   #defaultZone: http://127.0.0.1:10086/eureka
  #cloud:
    #nacos:
      #discovery:
        #cluster-name: HZ # 集群名称
        #namespace: 71774778-649a-4f6b-a592-ab6d9b66cb22  # nacos命名空间
        #ephemeral: false # 设置为非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
