server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        cluster-name: HZ # 集群名称
        #namespace: 71774778-649a-4f6b-a592-ab6d9b66cb22  # nacos命名空间
        ephemeral: false # 设置为非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则  优先选择本地集群
#eureka:
 #client:
  #service-url:
   #defaultZone: http://127.0.0.1:10086/eureka
#ribbon:
 #eager-load:    #开启饥饿加载
  #enabled: true
   #clients: userservice    #饥饿加载的服务名
feign:
  client:
    config:
      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: Basic #  日志级别
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数

